---
title: "Materiales testados para Epitraining"
author: "Zulma M. Cucunubá"
date: "2023-08-02"
output: md_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Kit de entrenamiento en Ciencia de datos en Salud Pública**

> # `e-Epi-training kit`

## **Motivación**

La formación en ciencia de datos ha adquirido una relevancia creciente
en el apoyo al manejo y respuesta de emergencias de salud pública, como
las epidemias y pandemias. Sin embargo, en Latinoamérica existe una
brecha significativa en la participación y representación de mujeres en
este campo, lo cual limita el potencial de desarrollo y avance en la
salud pública a nivel regional. Este proyecto promueve la implementación
de estrategias educativas innovadoras y e-learning que desafían las
barreras sociales, económicas y de acceso a educación de calidad
promoviendo transversalmente la equidad de género.

## **Objetivo**

Esta estrategia tiene como objetivo no solo aumentar el entrenamiento en
analítica de datos en salud pública promoviendo a la vez la equidad de
género.

## **Antecedentes**

La baja representación de las mujeres en áreas STEM es una preocupación
persistente que requiere de acciones concretas para promover la equidad
de género. En ciencia de datos la participación de mujeres en
comunidades como la de R en 2017 era del 17% y sólo un 9% del total de
autores de paquetes son mujeres. Promover la construcción de equidad de
género en ciencia de datos para salud pública es fundamental para
garantizar una representación diversa, perspectivas enriquecedoras y
estrategias más efectivas en emergencias sanitarias. Por esta razón,
desde el proyecto Epiverse TRACE-LAC iniciado a mediados de 2022, se
está construyendo una estrategia e-learning abierta, gratuita y en
español para el entrenamiento en análisis y respuesta a epidemias en
Latinoamérica y el Caribe.

## **Contenidos**

Esta estrategia incluye la generación de diversos tipos de contenido
(videos, podcasts, textos e imágenes), la integración de un enfoque de
género, y la promoción del uso de R para abordar los desafíos en la toma
de decisiones.

Para la construcción de la estrategia de entrenamiento e-learning se
tienen contempladas unidades cortas de aprendizaje agrupadas en cuatro
módulos principales:

1.  Módulo de Ciencia de datos y Salud pública
2.  Módulo de Teoría Epidémica y Epidemiológica
3.  Módulo de Respuesta a brotes
4.  Módulo de Modelamiento y analítica avanzada

Cada uno de estos módulos cuenta con varias unidades. Cada unidad tiene
un promedio de duración de trabajo entre 3-5 horas por parte del
estudiante, dependiendo de la ruta de ingreso y conocimientos previos.

## Fases del epi-training kit

Se plantearon cuatro fases para el análisis de necesidades, el diseño de
materiales y contenidos, la producción de recursos educativos y el
testeo de unidades para la implementación y evaluación.

#### **Fase 1. Exploratoria**

Esta fase tuvo lugar entre Agosto y Diciembre de 2022. Comprendió el
análisis de necesidades y desafíos de la posible comunidad de usuarios a
través de entrevistas, encuestas y entrenamientos presenciales en zonas
de fácil acceso geográfico en Colombia. Esta fase incluyó trabajo de
campo en ciudades como Bogotá, Manizales y Cali.

#### **Fase 2. Diseño y desarrollo**

Asimismo, en la fase de diseño y desarrollo se llevaron a cabo
entrenamientos en zonas con menor accesibilidad y la producción de
contenido de material e-learning. En la fase piloto se realizará el
testeo de las primeras unidades ampliando la participación de otros
países en Latinoamérica. Finalmente, en la fase de implementación y
evaluación se pondrá a disposición el producto final de manera abierta y
gratuita a personas en Latinoamérica y el Caribe.

Durante el desarrollo de las primeras fases se hizo uso de metodologías
de observación en terreno, mentimeter y nubes de palabras, cuestionarios
de caracterización de la población objetivo y encuestas de evaluación
sobre el contenido, material y metodología de los entrenamientos. Para
el piloto de la estrategia e-learning se contempla el desarrollo y
aplicación de un protocolo de usabilidad e incorporación de grupos
focales.

A lo largo de estas fases, la incorporación de la perspectiva de género
se ha planteado mediante: 1) Preguntar explícitamente aspectos
relacionados a género a los potenciales usuarios identificados; 2)
Identificar barreras de aprendizaje asociadas al género, 3) Promover la
participación de mujeres en el diseño y todas las fases del desarrollo,
4) Retroalimentar el diseño de acuerdo a los resultados preliminares
encontrados.

Resultados preliminares Entre 2022 y 2023 se han realizado cinco
entrenamientos en terreno que han incluido el uso de R. Más de 200
estudiantes y profesionales de las áreas STEM y salud han participado en
diferentes regiones de Colombia. Dentro de estos espacios se ha
promovido la formación de mujeres, con una participación de más del 60%.
A través de estos entrenamientos y de la revisión de literatura, se han
identificado elementos que resultan ser diferenciales en cuanto al
género para el aprendizaje de R y ciencia de datos para salud pública.
En el testeo de contenidos para la estrategia e-learning se han
identificado sesgos de género y la afectación de estos en el logro de
los objetivos de aprendizaje. Esto ha llevado a la elaboración e
implementación de una guía para la transversalidad del enfoque de género
en estrategias e-learning en ciencia de datos y salud pública, y el
diseño de una propuesta de unidad sobre "Datos con perspectiva de género
en salud pública". Se ha constatado que quienes más tienen visibilidad y
formación en programación en R y ciencia de datos para la salud son
hombres, por lo cual se están generando nuevas estrategias para
garantizar el acceso de mujeres a los entrenamientos, pilotos y la
estrategia e-learning. Se ha evidenciado que los roles marcados de
género, para las carreras de enfermería y medicina, afectan las
expectativas y los procesos de formación en ciencia de datos para el
análisis y respuesta a epidemias.
